version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    env_file:
      - ./database/.env

  # frontend:
  #   build: ./frontend
  #   # ports:
  #  

  # ml:
  #   build: ./ml
  #   