# version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    env_file:
      - ./database/.env   # or ./backend/.env if your .env is inside backend
  
  # frontend:
  #   build: 
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:80"
  #   depends_on:
  #     - backend
  #   restart: unless-stopped

  # frontend:
  #   build: ./frontend
  #   # ports:
  #   # command:

  # ml:
  #   build: ./ml
  #   # command: