# version: "3.9"
services:
  backend:
    image: spalkkina/7red:backend-latest
    ports:
      - "8000:8000"
    restart: unless-stopped
    env_file:
      - ./database/.env   
  
  frontend:
    image: spalkkina/7red:frontend-latest
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped
