name: CI/CD Pipeline

on:
  push:
    branches: [ deploy ]

env:
  DOCKER_HUB_REPO: ${{ secrets.DOCKER_HUB_USERNAME }}/7red
  BACKEND_TAG: backend-${{ github.sha }}
  FRONTEND_TAG: frontend-${{ github.sha }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          
      - name: Run tests
        run: |
          cd tests
          pytest -v tests.py


  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.VPS_SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Debug - Check SSH connection
        run: |
          echo "Проверяем подключение к серверу..."
          ssh -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} "echo 'SSH подключение успешно!'"

      - name: Prepare server environment
        run: |
          echo "Пытаемся создать папку /deploy/database..."
          ssh -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} <<EOF
            set -x  # Включим вывод выполняемых команд для отладки
            mkdir -p ~/deploy/database || {
              echo "Ошибка при создании папки! Проверьте права доступа."
              exit 1
            }
            echo "Проверяем, что папка создана:"
            ls -la ~/deploy
          EOF

      - name: Verify folder creation
        run: |
          echo "Проверяем результат создания папки:"
          ssh -o StrictHostKeyChecking=no \
              -o UserKnownHostsFile=/dev/null \
              ${{ secrets.VPS_USERNAME }}@${{ secrets.VPS_IP }} "ls -la /deploy"
      
      